[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  timeout = 26

[functions."consistency-check"]
  timeout = 26

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/appraisal-intake"
  to = "/appraisal-intake/index.html"
  status = 200

[[redirects]]
  from = "/consistency-check"
  to = "/consistency-check/index.html"
  status = 200
